export { default as CallToAction } from './CallToAction'
export { default as CustomerLogos } from './CustomerLogos'
export { default as FaqSection } from './FaqSection'
export { default as PricingTable } from './PricingTable'
export { default as SliderSection } from './SliderSection'
export { default as VideoHighlights } from './VideoHighlights'
